const List<String> pnleCategories = [
  'English',
  'Mathematics',
  'Logical Reasoning',
  'Mental Ability / Abstract',
];

final Map<String, List<String>> pnleKeyAreas = {
  'English': [
    'Synonym in context (sentence-based)',
    'Antonym in context (sentence-based)',
    'Vocabulary: academic words meaning',
    'Vocabulary: common idioms meaning',
    'Vocabulary: word usage in sentence',
    'Sentence completion using transition words',
    'Sentence completion using logical connectors',
    'Sentence completion (tone-based)',
    'Error identification (subject-verb agreement)',
    'Error identification (verb tense)',
    'Error identification (pronoun reference)',
    'Error identification (prepositions)',
    'Error identification (articles: a/an/the)',
    'Error identification (modifiers)',
    'Error identification (parallel structure)',
    'Sentence correction (grammar only)',
    'Sentence correction (clarity improvement)',
    'Sentence correction (conciseness)',
    'Sentence rearrangement (logical order)',
    'Paragraph organization (coherence)',
    'Short reading: main idea',
    'Short reading: supporting detail',
    'Short reading: inference',
    'Short reading: tone identification',
    'Short reading: author\'s purpose',
    'Context clues (meaning of word)',
    'Context clues (phrase meaning)',
    'Logical connectors (cause-effect)',
    'Logical connectors (contrast)',
    'Logical connectors (addition)',
    'Logical connectors (sequence)',
    'Verb form consistency',
    'Active vs passive voice correction',
    'Redundancy elimination',
    'Word choice precision',
    'Sentence fragment identification',
    'Run-on sentence correction',
    'Capitalization rules',
    'Punctuation (comma usage)',
    'Punctuation (semicolon usage)',
    'Punctuation (apostrophe usage)',
    'Punctuation (quotation marks)',
    'Formal vs informal tone',
    'Sentence emphasis (best placement)',
    'Ambiguity resolution',
    'Misplaced modifier correction',
    'Double negative correction',
    'Comparative vs superlative usage',
    'Agreement (pronoun-antecedent)',
    'Cohesion (reference words like this/that/these)',
  ],
  'Mathematics': [
    'Linear equation solving (one variable)',
    'Linear equation with fractions',
    'Translating words to algebraic equation',
    'Evaluating algebraic expressions',
    'Ratio (basic comparison)',
    'Ratio (word problems)',
    'Proportion solving',
    'Percentage increase (word problem)',
    'Percentage decrease (word problem)',
    'Reverse percentage (original value)',
    'Discount problems',
    'Markup problems',
    'Simple interest',
    'Average (basic)',
    'Average (missing value)',
    'Distance = rate x time problems',
    'Work problems (combined work)',
    'Age problems',
    'Number problems (consecutive integers)',
    'Mixture problems',
    'Fraction operations (addition/subtraction)',
    'Fraction operations (multiplication/division)',
    'Decimal operations',
    'Order of operations (PEMDAS)',
    'Exponents (basic laws)',
    'Square roots (estimation)',
    'Inequalities (basic solving)',
    'Inequalities (word problems)',
    'Absolute value (basic)',
    'Absolute value (equations)',
    'Geometry: perimeter',
    'Geometry: area (rectangle/triangle)',
    'Geometry: circle (basic concepts)',
    'Geometry: circumference',
    'Geometry: word problems',
    'Probability (basic)',
    'Probability (simple events)',
    'Combinations (basic counting)',
    'Sequences (arithmetic)',
    'Sequences (find next term)',
    'Patterns (number patterns)',
    'Speed math (mental multiplication)',
    'Speed math (division shortcuts)',
    'Estimation techniques',
    'Data interpretation (simple table)',
    'Data interpretation (word problem)',
    'Graph reading (basic)',
    'Graph interpretation (trend)',
    'Algebra: distributive property',
    'Algebra: simplifying expressions',
  ],
  'Logical Reasoning': [
    'Letter analogy (A:B :: C:?)',
    'Number analogy',
    'Word analogy (meaning relationship)',
    'Synonym analogy',
    'Antonym analogy',
    'Cause-effect reasoning',
    'Statement and conclusion',
    'Assumption identification',
    'Strengthen the argument',
    'Weaken the argument',
    'Logical sequence (events)',
    'Odd one out (category-based)',
    'Odd one out (pattern-based)',
    'Deductive reasoning (if-then)',
    'Syllogism (all/some/none)',
    'Logical consistency check',
    'Inference from statements',
    'Conditional reasoning',
    'Argument flaw identification',
    'Generalization vs specific',
    'Classification logic',
    'Series completion (letters)',
    'Series completion (numbers)',
    'Series completion (mixed pattern)',
    'Coding-decoding (letter shift)',
    'Coding-decoding (symbol mapping)',
    'Direction sense (left-right logic)',
    'Ranking and ordering',
    'Seating arrangement (basic)',
    'Matching type logic',
    'Data sufficiency (basic)',
    'Statement equivalence',
    'Logical grouping',
    'Cause vs correlation',
    'Deductive elimination',
    'Pattern rule identification',
    'Input-output pattern logic',
    'Calendar logic (basic)',
    'Clock logic (basic)',
    'Logical puzzle (short)',
    'Relationship logic (family)',
    'Assertion and reason',
    'Venn diagram logic (basic)',
    'Set inclusion logic',
    'Contradiction detection',
    'Logical chain reasoning',
    'Rule application problems',
    'Constraint-based reasoning',
    'Multi-step deduction',
    'Minimal condition reasoning',
  ],
  'Mental Ability / Abstract': [
    'Symbol sequence pattern',
    'Letter pattern progression',
    'Number pattern progression',
    'Alternating pattern detection',
    'Increasing/decreasing pattern',
    'Position-based pattern',
    'Mirror pattern (text simulation)',
    'Rotation logic (described shapes)',
    'Code substitution (A=1 variations)',
    'Code substitution (custom mapping)',
    'Matrix pattern (row rule)',
    'Matrix pattern (column rule)',
    'Matrix pattern (combined rule)',
    'Odd one out (symbol pattern)',
    'Odd one out (sequence break)',
    'Pattern completion (missing term)',
    'Series with 2-step logic',
    'Series with 3-step logic',
    'Frequency pattern',
    'Repetition pattern',
    'Grouping pattern',
    'Symmetry logic (text-based)',
    'Embedded pattern detection',
    'Pair relationship pattern',
    'Mapping pattern',
    'Transformation pattern',
    'Rule switching pattern',
    'Direction pattern (text arrows)',
    'Visual logic (described shapes)',
    'Binary pattern (0/1 style)',
    'Arithmetic pattern mix',
    'Alphabet-number mix pattern',
    'Grid logic (text version)',
    'Missing element in grid',
    'Pattern elimination',
    'Pattern matching',
    'Progressive transformation',
    'Cyclic pattern',
    'Nested pattern',
    'Reverse pattern',
    'Doubling/halving pattern',
    'Pattern with exceptions',
    'Multi-rule pattern',
    'Symbol hierarchy logic',
    'Pattern compression',
    'Pattern expansion',
    'Sequence interruption detection',
    'Pattern prediction',
    'Rule inference from examples',
    'Pattern validation (which fits rule)',
  ],
};

List<String> getAllSpecializations() {
  return List<String>.from(pnleCategories);
}

