const List<String> pnleCategories = [
  'Language Proficiency',
  'Reading Comprehension',
  'Mathematics',
  'Science',
];

final Map<String, List<String>> pnleKeyAreas = {
  'Language Proficiency': [
    'Context clues',
    'Multiple meaning words',
    'Denotation and connotation',
    'Synonyms in context',
    'Antonyms in context',
    'Word roots',
    'Prefixes and suffixes',
    'Idiomatic expressions',
    'Figurative language meaning',
    'Academic vocabulary',
    'Tone based word choice',
    'Register formal and informal',
    'Precision of word usage',
    'Word meaning from paragraph context',
    'Subject verb agreement',
    'Verb tense consistency',
    'Correct verb forms',
    'Pronoun antecedent agreement',
    'Pronoun reference clarity',
    'Modifiers and placement',
    'Parallel structure',
    'Prepositions usage',
    'Articles usage',
    'Comparison forms',
    'Active and passive voice',
    'Sentence fragments',
    'Run on sentences',
    'Capitalization rules',
    'Punctuation usage',
    'Logical connectors',
    'Cause and effect relationships',
    'Contrast relationships',
    'Sequence and time order',
    'Condition and result',
    'Purpose and reason',
    'Tone and mood consistency',
    'Context appropriate vocabulary',
    'Grammar fit within sentence',
    'Parallel structure completion',
    'Idea completion and coherence',
    'Eliminating illogical choices',
    'Subject verb agreement errors',
    'Verb tense errors',
    'Pronoun agreement errors',
    'Misplaced modifiers',
    'Dangling modifiers',
    'Faulty comparisons',
    'Parallelism errors',
    'Incorrect preposition usage',
    'Article usage errors',
    'Sentence fragments errors',
    'Run on sentence errors',
    'Capitalization errors',
    'Punctuation errors',
    'Synonym relationships',
    'Antonym relationships',
    'Part to whole relationships',
    'Whole to part relationships',
    'Cause to effect relationships',
    'Effect to cause relationships',
    'Function relationships',
    'Degree relationships',
    'Sequence relationships',
    'Object and purpose relationships',
    'Classification relationships',
    'Analogy reasoning',
    'Topic sentence identification',
    'Supporting detail relevance',
    'Logical sentence order',
    'Transitional words usage',
    'Unity of ideas',
    'Coherence of paragraph',
    'Sentence placement',
    'Irrelevant sentence identification',
    'Paragraph conclusion',
    'Consistency of tone',
    'Consistency of point of view',
  ],
  'Reading Comprehension': [
    'Central idea identification',
    'Author purpose identification',
    'Best title selection',
    'Topic versus main idea',
    'Overall message understanding',
    'Passage summary selection',
    'Purpose of paragraph',
    'Thesis statement identification Explicit detail identification',
    'Fact versus opinion',
    'Supporting example recognition',
    'Evidence based questions',
    'Detail location skills',
    'Reference words identification',
    'Detail accuracy checking Logical inference making',
    'Implied idea recognition',
    'Conclusion drawing',
    'Author assumption identification',
    'Predicting outcomes',
    'Meaning beyond text',
    'Reasoning from clues Word meaning from context',
    'Context clue usage',
    'Meaning shift in passage',
    'Academic word interpretation',
    'Figurative word meaning',
    'Tone based word meaning',
    'Synonym replacement in passage Author attitude identification',
    'Emotional tone recognition',
    'Mood of passage',
    'Positive negative neutral tone',
    'Opinion indicators',
    'Word choice effect',
    'Bias detection Cause and effect structure',
    'Comparison and contrast structure',
    'Problem and solution structure',
    'Sequence of events',
    'Chronological order',
    'Paragraph function identification',
    'Signal words identification',
  ],
  'Mathematics': [
    'Whole numbers operations',
    'Fractions operations',
    'Decimals operations',
    'Percent concepts',
    'Number properties',
    'Order of operations',
    'Estimation and rounding',
    'Number sense comparison',
    'Algebraic expressions evaluation',
    'Translating words to expressions',
    'Linear equations',
    'Simple inequalities',
    'Exponents and powers',
    'Polynomials basics',
    'Substitution method',
    'Equation solving strategies',
    'Plane figures properties',
    'Angles relationships',
    'Triangles properties',
    'Quadrilaterals properties',
    'Circles basics',
    'Perimeter and area',
    'Volume of solids',
    'Coordinate plane basics',
    'Ratio and proportion problems',
    'Rate and speed problems',
    'Work problems',
    'Age problems',
    'Mixture problems',
    'Cost and profit problems',
    'Distance problems',
    'Multi step word problems',
    'Reading tables and charts',
    'Reading graphs',
    'Mean median mode',
    'Range interpretation',
    'Probability basics',
    'Data comparison',
    'Trend interpretation',
    'Number patterns',
    'Sequence completion',
    'Logic puzzles',
    'Elimination strategies',
    'Problem solving heuristics',
    'Non routine problems',
    'Pattern recognition',
  ],
  'Science': [
    'Cell structure and function',
    'Plant and animal systems',
    'Photosynthesis and respiration',
    'Genetics basics',
    'Heredity and traits',
    'Evolution concepts',
    'Ecology and environment',
    'Human body systems',
    'Atomic structure',
    'Elements and compounds',
    'Chemical reactions',
    'Acids and bases',
    'States of matter',
    'Periodic table basics',
    'Solutions and mixtures',
    'Conservation of mass',
    'Motion and forces',
    'Work and energy',
    'Power concepts',
    'Heat and temperature',
    'Electricity basics',
    'Magnetism basics',
    'Waves and sound',
    'Light and optics',
    'Earth layers',
    'Weather and climate',
    'Water cycle',
    'Astronomy basics',
    'Earth rotation and revolution',
    'Natural resources',
    'Environmental issues',
    'Scientific method steps',
    'Variables and controls',
    'Experimental design',
    'Measurement and units',
    'Tools and instruments',
    'Scientific reasoning',
    'Interpreting graphs and tables',
    'Analyzing experimental data',
    'Identifying trends',
    'Drawing conclusions',
    'Error and accuracy',
  ],
};

List<String> getAllSpecializations() {
  return List<String>.from(pnleCategories);
}
