const List<String> pnleCategories = [
  'Mental Ability',
  'English',
  'Mathematics',
  'Science',
];

final Map<String, List<String>> pnleKeyAreas = {
  'Mental Ability': [
    'abstract pattern completion',
    'figure series progression',
    'number series increasing',
    'number series decreasing',
    'alternating number series',
    'letter series progression',
    'alphanumeric series',
    'analogy word-based',
    'analogy number-based',
    'analogy figure-based',
    'classification words',
    'classification numbers',
    'classification figures',
    'odd one out words',
    'odd one out numbers',
    'odd one out figures',
    'logical reasoning statements',
    'syllogism basic',
    'syllogism conclusion validity',
    'coding letter shift',
    'coding number pattern',
    'coding mixed symbols',
    'decoding patterns',
    'directional reasoning simple',
    'directional reasoning complex',
    'spatial rotation',
    'mirror images figures',
    'mirror images letters',
    'paper folding prediction',
    'paper cutting patterns',
    'embedded figures',
    'figure counting',
    'matrix reasoning 2x2',
    'matrix reasoning 3x3',
    'sequence ordering events',
    'ranking and ordering',
    'venn diagram reasoning',
    'cause and effect reasoning',
    'assumption identification',
    'conclusion drawing',
    'statement evaluation',
    'input-output pattern',
    'visual analogy',
    'symbol substitution',
  ],
  'English': [
    'reading comprehension main idea',
    'reading comprehension supporting details',
    'reading comprehension inference',
    'reading comprehension tone',
    'reading comprehension author purpose',
    'vocabulary synonyms',
    'vocabulary antonyms',
    'vocabulary context clues',
    'vocabulary word usage',
    'grammar subject verb agreement',
    'grammar verb tenses',
    'grammar pronoun usage',
    'grammar modifiers',
    'grammar prepositions',
    'grammar conjunctions',
    'grammar articles',
    'grammar sentence structure',
    'grammar fragments and run-ons',
    'grammar parallelism',
    'sentence completion basic',
    'sentence completion context-based',
    'error identification grammar',
    'error identification punctuation',
    'spelling recognition',
    'capitalization rules',
    'paragraph organization logical order',
    'paragraph organization transitions',
    'paragraph coherence',
    'paragraph unity',
    'identifying topic sentence',
    'identifying supporting sentence',
    'identifying irrelevant sentence',
    'sentence improvement',
    'sentence rearrangement',
    'idioms and expressions',
    'figurative language',
    'analogy words',
    'word formation prefixes',
    'word formation suffixes',
    'word formation roots',
    'punctuation commas',
    'punctuation periods',
    'punctuation apostrophes',
    'punctuation quotation marks',
    'punctuation colons and semicolons',
    'direct and indirect speech',
    'active and passive voice',
    'cloze test passages',
    'short passage analysis',
    'long passage analysis',
  ],
  'Mathematics': [
    'basic operations integers',
    'order of operations',
    'fractions addition subtraction',
    'fractions multiplication division',
    'decimals operations',
    'percent basic',
    'percent increase decrease',
    'ratio and proportion',
    'direct variation',
    'inverse variation',
    'averages mean median mode',
    'algebra simplifying expressions',
    'algebra linear equations',
    'algebra word problems linear',
    'algebra inequalities',
    'algebra systems of equations',
    'algebra exponents laws',
    'algebra radicals',
    'algebra polynomials operations',
    'algebra factoring trinomials',
    'algebra factoring special products',
    'algebra quadratic equations',
    'geometry points lines planes',
    'geometry angles',
    'geometry triangles properties',
    'geometry triangle similarity',
    'geometry triangle congruence',
    'geometry quadrilaterals',
    'geometry circles properties',
    'geometry arcs and sectors',
    'geometry perimeter',
    'geometry area',
    'geometry surface area',
    'geometry volume',
    'coordinate geometry distance',
    'coordinate geometry midpoint',
    'coordinate geometry slope',
    'coordinate geometry equation of line',
    'coordinate geometry graph interpretation',
    'trigonometry basic ratios',
    'trigonometry angles',
    'statistics data interpretation tables',
    'statistics graphs interpretation',
    'statistics probability basic',
    'statistics mean median mode',
    'number properties divisibility rules',
    'number properties prime numbers',
    'number properties lcm and gcf',
    'sequences arithmetic',
    'sequences geometric',
    'word problems mixture',
    'word problems work rate',
    'word problems distance speed time',
    'word problems age problems',
    'word problems interest simple',
    'estimation and rounding',
  ],
  'Science': [
    'scientific method steps',
    'scientific method variables',
    'scientific method experiment design',
    'scientific reasoning cause and effect',
    'scientific reasoning hypothesis testing',
    'data interpretation graphs',
    'data interpretation tables',
    'biology cell structure',
    'biology cell function',
    'biology mitosis and meiosis',
    'biology genetics basic',
    'biology dna and rna',
    'biology human digestive system',
    'biology human circulatory system',
    'biology human respiratory system',
    'biology human nervous system',
    'biology human reproductive system',
    'biology homeostasis',
    'biology ecosystems',
    'biology food chains and webs',
    'biology evolution basic',
    'biology plant structure',
    'biology photosynthesis',
    'biology cellular respiration',
    'chemistry matter classification',
    'chemistry physical and chemical changes',
    'chemistry atomic structure',
    'chemistry periodic table trends',
    'chemistry chemical bonding',
    'chemistry chemical reactions types',
    'chemistry balancing equations',
    'chemistry solutions and mixtures',
    'chemistry acids and bases',
    'chemistry concentration',
    'physics motion kinematics',
    'physics speed velocity acceleration',
    'physics force newtons laws',
    'physics work power energy',
    'physics potential and kinetic energy',
    'physics heat and temperature',
    'physics waves properties',
    'physics sound and light',
    'physics electricity basics',
    'physics circuits',
    'physics magnetism',
    'earth science layers of earth',
    'earth science rocks and minerals',
    'earth science plate tectonics',
    'earth science earthquakes',
    'earth science volcanoes',
    'earth science weather',
    'earth science climate',
    'earth science water cycle',
    'earth science atmosphere layers',
    'earth science solar system',
    'earth science planets',
    'earth science moon phases',
    'earth science eclipses',
    'earth science seasons',
    'environmental science pollution',
    'environmental science conservation',
    'everyday science applications',
    'applied science technology basics',
  ],
};

List<String> getAllSpecializations() {
  return List<String>.from(pnleCategories);
}

