// File generated by hand from google-services.json
// This file defines Firebase options for all platforms

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBunHIlRqFvMOlhgmxUE8OwK8nBuKE0P6k',
    appId: '1:144149624587:android:d77cfed343741f1a26d40e',
    messagingSenderId: '144149624587',
    projectId: 'pnle-reviewer-ios',
    storageBucket: 'pnle-reviewer-ios.firebasestorage.app',
    databaseURL: 'https://pnle-reviewer-ios-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqwkTIYOp801fJuv1o7j834KcRBFnPsHg',
    appId: '1:144149624587:ios:8dad19b37f33ae9b26d40e',
    messagingSenderId: '144149624587',
    projectId: 'pnle-reviewer-ios',
    storageBucket: 'pnle-reviewer-ios.firebasestorage.app',
    databaseURL: 'https://pnle-reviewer-ios-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnjvefkmr7eCrI-xnPrRv6mxZwFqfWAA',
    appId: '1:14765051159:web:1f472f07eed3c00f76fb52',
    messagingSenderId: '14765051159',
    projectId: 'pnle-reviewer-ios',
    storageBucket: 'pnle-reviewer-ios.firebasestorage.app',
    databaseURL: 'https://pnle-reviewer-ios-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
