// File generated by hand from google-services.json
// This file defines Firebase options for all platforms

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg65dv4DYHn7B_Ys2AHfI-sfvGayZeHBU',
    appId: '1:214718638699:android:648e865e895cfae4ac5f2e',
    messagingSenderId: '214718638699',
    projectId: 'upcat-ios',
    storageBucket: 'upcat-ios.firebasestorage.app',
    databaseURL: 'https://ustet-reviewer-2027-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmj6TCl8g--Ay-PntRZv-pDVIGjCr4Dr8',
    appId: '1:214718638699:ios:bf497385b6c9776aac5f2e',
    messagingSenderId: '214718638699',
    projectId: 'upcat-ios',
    storageBucket: 'upcat-ios.firebasestorage.app',
    databaseURL: 'https://ustet-reviewer-2027-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnjvefkmr7eCrI-xnPrRv6mxZwFqfWAA',
    appId: '1:14765051159:web:1f472f07eed3c00f76fb52',
    messagingSenderId: '14765051159',
    projectId: 'upcat-ios',
    storageBucket: 'upcat-ios.firebasestorage.app',
    databaseURL: 'https://ustet-reviewer-2027-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
